from pyspark.sql import SparkSession, DataFrame
from pyspark.sql.functions import from_json, col, sum, count, to_json, struct
from pyspark.sql.types import StructType, StructField, StringType, DoubleType, LongType, BooleanType


CHECKPOINT_DIR = "/mnt/spark-checkpoints"
STATE_DIR = "/mnt/spark-state"

KAKFA_BROKERS = "kafka-broker-1:19092,kafka-broker-2:19092,kafka-broker-3:19092"
TRANSACTION_TOPIC = "financial_transactions"
AGGREGATES_TOPIC = "transaction_aggregates"
ANOMALIES_TOPIC = "transaction_anomalies"


# setup
# ----------------------------------------------------------------------------#
spark = ( SparkSession.builder.appName("FinancialTransactionProcessor")
    .config("spark.sql.streaming.checkpointLocation", CHECKPOINT_DIR)
    .config("spark.sql.streaming.stateStore.stateStoreDir", STATE_DIR)
    .config("spark.sql.shuffle.partitions", 20)
    # .config("spark.jars.packages", )
    .getOrCreate()
)

spark.sparkContext.setLogLevel("WARN")

transaction_schema = StructType([
    StructField("transactionId", StringType(), False),
    StructField("userId", StringType(), False),
    StructField("amount", DoubleType(), False),
    StructField("transactionTime", LongType(), False),
    StructField("merchantId", StringType(), False),
    StructField("transactionType", StringType(), False),
    StructField("location", StringType(), False),
    StructField("paymentMethod", StringType(), False),
    StructField("isInternational", BooleanType(), False),
    StructField("currency", StringType(), False),
])

kafka_stream = ( spark.readStream
    .format("kafka")
    .option("kafka.bootstrap.servers", KAKFA_BROKERS)
    .option('subscribe', TRANSACTION_TOPIC)
    .option("startingOffsets", "earliest")
    .load()
)
# ----------------------------------------------------------------------------#


# get the transaction events
# ----------------------------------------------------------------------------#
transaction_df = kafka_stream.selectExpr(
    "CAST(value AS STRING)" # our kafka messags are json-formatted strings
).select(
    from_json(col=col("value"), schema=transaction_schema).alias("data") # convert the json formatted string to the transction_schema format
).select("data.*")
# ----------------------------------------------------------------------------#


# find anomalies and send them to their own topic
# ----------------------------------------------------------------------------#
anomalies_df = transaction_df.filter(col("amount") > 15000) # if transaction amount is generated by the log-normal distribution with the function's mean argument set to 30, use 15000 here

anomalies_kafka_df = anomalies_df.withColumn(
    "key", col("transactionId")
).withColumn(
    "value", to_json(struct([col(c) for c in anomalies_df.columns])) # we want all the data
)

_ = anomalies_kafka_df.selectExpr("key", "value") \
    .writeStream \
    .format("kafka") \
    .outputMode("update") \
    .option("kafka.bootstrap.servers", KAKFA_BROKERS) \
    .option("topic", ANOMALIES_TOPIC) \
    .option("checkpointLocation", f"{CHECKPOINT_DIR}/anomalies") \
    .start(queryName="Anomaly Finder")
# ----------------------------------------------------------------------------#


# calculate aggregations (merchant performance) for each microbatch and send them to their own topic
# ----------------------------------------------------------------------------#
def aggregate_batch(transaction_df: DataFrame, batch_id):
    merchant_performance_df = ( transaction_df.groupBy("merchantId")
        .agg(
            sum("amount").alias("totalAmount"),
            count("*").alias("transactionCount")
        )
    )

    # change the merchant_performance_df to a format we can send to kafka
    merchant_performance_df_kafka = ( merchant_performance_df
        .withColumn("key", col("merchantId"))
        .withColumn(
            "value",
            to_json(
                struct(
                    col("merchantId"),
                    col("totalAmount"),
                    col("transactionCount")
                )
            )
        )
    )

    ( 
        merchant_performance_df_kafka
            .select("key", "value")
            .write
            .format("kafka")
            .option("kafka.bootstrap.servers", KAKFA_BROKERS)
            .option("topic", AGGREGATES_TOPIC)
            .save()
    )


_ = ( 
    transaction_df.writeStream
        .foreachBatch(aggregate_batch)
        .option("checkpointLocation", f"{CHECKPOINT_DIR}/merchant_performance")
        .start(queryName="Merchant Performance Aggregator")
)
# ----------------------------------------------------------------------------#

# run all streams till termination
# (The .awaitAnyTermination() can be called on an individual stream also. e.g. output of transaction_df.writeStream.start())
spark.streams.awaitAnyTermination()